// This would be YOUR production AWS Account ID (where SpotSave backend runs)
export const SPOTSAVE_AWS_ACCOUNT_ID = "123456789012";

export const STACK_NAME = "SpotSave-Access-Role";

// Link to the CloudFormation Create Stack page (Upload mode)
export const CF_CONSOLE_URL = "https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/template";

// Embedded Template to avoid S3 hosting dependencies for the demo
export const CF_TEMPLATE_BODY = `
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Saves Integration Role: Creates a secure, read-only role for cloud cost analysis by Saves.'

Parameters:
  SpotSaveAccountId:
    Type: String
    Description: 'The AWS Account ID of the Saves platform (do not change unless instructed).'
    Default: '123456789012'
    AllowedPattern: '^\\d{12}$'
  
  ExternalId:
    Type: String
    Description: 'Unique security identifier generated by Saves for your account.'
    MinLength: 10

Resources:
  SpotSaveAnalysisRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'Saves-Analysis-Role-\${ExternalId}'
      Description: 'Allows Saves (Pandey Solutions) to perform read-only cost and security analysis.'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::\${SpotSaveAccountId}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
        - 'arn:aws:iam::aws:policy/job-function/ViewOnlyAccess'
      Policies:
        - PolicyName: SavesCostAnalysis
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ce:GetCostAndUsage'
                  - 'ce:GetCostForecast'
                  - 'ce:GetReservation*'
                  - 'ce:GetSavingsPlans*'
                  - 'compute-optimizer:Get*'
                  - 'compute-optimizer:Export*'
                  - 'savingsplans:Describe*'
                  - 'support:DescribeTrustedAdvisor*'
                  - 'cur:DescribeReportDefinitions'
                Resource: '*'

Outputs:
  RoleArn:
    Description: 'The ARN of the created role to paste into Saves dashboard.'
    Value: !GetAtt SpotSaveAnalysisRole.Arn
`.trim();
